/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Estructuras_de_datos.ListaSimple;
import javax.swing.JLabel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @authors Luis Peña, Luis Lovera y Diego Linares.
 * Descripción de la clase: 
 */
public class Interfaz1 extends javax.swing.JFrame {
    private JLabel[][] tablero; //simula el tablero como una matriz de JLabels.
    private ListaSimple diccionario; //Es una lista con las palabras del diccionario.
    private char[][] tableroLetras;
    private javax.swing.JTextArea textAreaDic; 
    /**
     * Creates new form NewJFrame
     */
    public Interfaz1() {
        
        initComponents();
        diccionario = new ListaSimple();
        tablero = new JLabel[4][4];
        tableroLetras = new char[4][4];
        
        tablero[0][0] = Jlabel00;
        tablero[0][1] = Jlabel01;
        tablero[0][2] = Jlabel02;
        tablero[0][3] = Jlabel03;
        tablero[1][0] = Jlabel10;
        tablero[1][1] = Jlabel11;
        tablero[1][2] = Jlabel12;
        tablero[1][3] = Jlabel13;
        tablero[2][0] = Jlabel20;
        tablero[2][1] = Jlabel21;
        tablero[2][2] = Jlabel22;
        tablero[2][3] = Jlabel23;
        tablero[3][0] = Jlabel30;
        tablero[3][1] = Jlabel31;
        tablero[3][2] = Jlabel32;
        tablero[3][3] = Jlabel33;
        
        /* Código para probar el correcto funcionamiento del tablero.
        char[] cadena = {'a','b','c','d','a','b','c','d','a','b','c','d','a','b','c','d'};
        
        int k = 0;
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                tablero[i][j].setText(String.valueOf(cadena[k]));
                k++;
            }    
        }*/
    }
    
    /**
     * Permite al usuario escoger un archivo y cargarlo. Después mostrará las palabras del diccionario en el "textArea#" y llamará al método GenerarTablero(). 
     */
    public void CargarArchivoTXT() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // Limpiar el tablero visual y de datos antes de cargar
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 4; j++) {
                    tableroLetras[i][j] = '\u0000'; // Resetear datos
                    tablero[i][j].setText("");     // Limpiar JLabels
                }
            }

            try (BufferedReader text = new BufferedReader(new FileReader(selectedFile))) {
                String line = text.readLine();
                String[] letters = line.trim().toUpperCase().split(",");
                
                // Validar que sean exactamente 16 elementos
                if (letters.length != 16) {
                    throw new IOException("El archivo no ccumple con los requerimientos de la sopa.");
                }

                // Cargar las letras en el array de tableroLetras
                int k = 0;
                for (int i = 0; i < 4; i++) {
                    for (int j = 0; j < 4; j++) {
                        if (letters[k].trim().isEmpty()) {
                             throw new IOException("El elemento en la posición " + (k + 1) + " está vacío.");
                        }
                        tableroLetras[i][j] = letters[k].trim().charAt(0);
                        k++;
                    }
                }

                GenerarTablero();
                JOptionPane.showMessageDialog(this, "Tablero cargado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }
    
    /**
     * 
     */
    public void GenerarTablero(){
        
    }
    
    /**
     * 
     */
    public void GuardarDiccionario(){
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cargar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        busquedaA = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        busquedaE = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        Jlabel03 = new javax.swing.JLabel();
        Jlabel00 = new javax.swing.JLabel();
        Jlabel01 = new javax.swing.JLabel();
        Jlabel02 = new javax.swing.JLabel();
        Jlabel13 = new javax.swing.JLabel();
        Jlabel10 = new javax.swing.JLabel();
        Jlabel11 = new javax.swing.JLabel();
        Jlabel12 = new javax.swing.JLabel();
        Jlabel23 = new javax.swing.JLabel();
        Jlabel20 = new javax.swing.JLabel();
        Jlabel21 = new javax.swing.JLabel();
        Jlabel22 = new javax.swing.JLabel();
        Jlabel33 = new javax.swing.JLabel();
        Jlabel30 = new javax.swing.JLabel();
        Jlabel31 = new javax.swing.JLabel();
        Jlabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SOPA DE LETRAS");
        getContentPane().add(titulo);
        titulo.setBounds(430, 20, 190, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Presionar el botón para cargar un diccionario y generar el tablero:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 540, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Diccionario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 140, 150, 25);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 170, 330, 230);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tablero");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 140, 80, 25);

        cargar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargar.setText("Cargar archivo");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        getContentPane().add(cargar);
        cargar.setBounds(550, 90, 160, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccionar método de búsqueda y presionar el botón para buscar palabras del diccionario:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 420, 750, 25);

        busquedaA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busquedaA.setText("Búsqueda automática");
        busquedaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaAActionPerformed(evt);
            }
        });
        getContentPane().add(busquedaA);
        busquedaA.setBounds(120, 460, 190, 40);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BFS", "DFS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(30, 460, 72, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 520, 280, 120);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("El tiempo total de búsqueda fue de X segundos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 560, 400, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Rellene el campo vacío con la palabra que desea buscar en el tablero:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 670, 730, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 710, 250, 40);

        busquedaE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busquedaE.setText("Buscar palabra");
        busquedaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaEActionPerformed(evt);
            }
        });
        getContentPane().add(busquedaE);
        busquedaE.setBounds(300, 710, 160, 40);

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton20.setText("Guardar Diccionario");
        getContentPane().add(jButton20);
        jButton20.setBounds(30, 790, 190, 60);

        reiniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar);
        reiniciar.setBounds(820, 790, 180, 60);

        Jlabel03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel03.setText("03");
        Jlabel03.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel03);
        Jlabel03.setBounds(810, 170, 80, 50);

        Jlabel00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel00.setText("00");
        Jlabel00.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel00);
        Jlabel00.setBounds(540, 170, 80, 50);

        Jlabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel01.setText("01");
        Jlabel01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel01);
        Jlabel01.setBounds(630, 170, 80, 50);

        Jlabel02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel02.setText("02");
        Jlabel02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel02);
        Jlabel02.setBounds(720, 170, 80, 50);

        Jlabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel13.setText("13");
        Jlabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel13);
        Jlabel13.setBounds(810, 230, 80, 50);

        Jlabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel10.setText("10");
        Jlabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel10);
        Jlabel10.setBounds(540, 230, 80, 50);

        Jlabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel11.setText("11");
        Jlabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel11);
        Jlabel11.setBounds(630, 230, 80, 50);

        Jlabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel12.setText("12");
        Jlabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel12);
        Jlabel12.setBounds(720, 230, 80, 50);

        Jlabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel23.setText("23");
        Jlabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel23);
        Jlabel23.setBounds(810, 290, 80, 50);

        Jlabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel20.setText("20");
        Jlabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel20);
        Jlabel20.setBounds(540, 290, 80, 50);

        Jlabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel21.setText("21");
        Jlabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel21);
        Jlabel21.setBounds(630, 290, 80, 50);

        Jlabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel22.setText("22");
        Jlabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel22);
        Jlabel22.setBounds(720, 290, 80, 50);

        Jlabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel33.setText("33");
        Jlabel33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel33);
        Jlabel33.setBounds(810, 350, 80, 50);

        Jlabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel30.setText("30");
        Jlabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel30);
        Jlabel30.setBounds(540, 350, 80, 50);

        Jlabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel31.setText("31");
        Jlabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel31);
        Jlabel31.setBounds(630, 350, 80, 50);

        Jlabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlabel32.setText("32");
        Jlabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(Jlabel32);
        Jlabel32.setBounds(720, 350, 80, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaAActionPerformed
        // TODO add your handling code here:
        //Búsqueda automática hecha por el método de búsqueda seleccionado 
    }//GEN-LAST:event_busquedaAActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
        //Reinicia los atributos y JTextField para empezar de nuevo sin necesidad de cerrrar y abrir la interfaz nuevamente. 
    }//GEN-LAST:event_reiniciarActionPerformed

    private void busquedaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaEActionPerformed
        // TODO add your handling code here:
        //Búsqueda específica hecha siempre con el método de búsqueda BFS
    }//GEN-LAST:event_busquedaEActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
        CargarArchivoTXT();
    }//GEN-LAST:event_cargarActionPerformed


    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel00;
    private javax.swing.JLabel Jlabel01;
    private javax.swing.JLabel Jlabel02;
    private javax.swing.JLabel Jlabel03;
    private javax.swing.JLabel Jlabel10;
    private javax.swing.JLabel Jlabel11;
    private javax.swing.JLabel Jlabel12;
    private javax.swing.JLabel Jlabel13;
    private javax.swing.JLabel Jlabel20;
    private javax.swing.JLabel Jlabel21;
    private javax.swing.JLabel Jlabel22;
    private javax.swing.JLabel Jlabel23;
    private javax.swing.JLabel Jlabel30;
    private javax.swing.JLabel Jlabel31;
    private javax.swing.JLabel Jlabel32;
    private javax.swing.JLabel Jlabel33;
    private javax.swing.JButton busquedaA;
    private javax.swing.JButton busquedaE;
    private javax.swing.JButton cargar;
    private javax.swing.JButton jButton20;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
